"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { CheckCircle2, MessageCircle, RefreshCw } from "lucide-react";

type Status = "received" | "confirmed" | "billed" | "ready_for_collection" | "collected" | "cancelled";
type SalesCase = { id: string; reference: string; status: Status; customerName: string; customerPhone: string; productName: string; quantity: number; totalMinor: number | null; billNumber: string | null; collectionNote: string; createdAt: string };
const next: Partial<Record<Status, { status: Status; label: string }>> = { received: { status: "confirmed", label: "Confirm order" }, confirmed: { status: "billed", label: "Prepare bill" }, billed: { status: "ready_for_collection", label: "Ready for collection" }, ready_for_collection: { status: "collected", label: "Mark collected" } };

export function WalkInOrders() {
  const [items,setItems]=useState<SalesCase[]>([]); const [selected,setSelected]=useState<SalesCase>(); const [message,setMessage]=useState("Loading orders…");
  const load=useCallback(async()=>{ try{const response=await fetch("/api/v1/admin/walk-in-orders",{credentials:"include"}); if(!response.ok)throw new Error(); const data=await response.json() as {items:SalesCase[]}; setItems(data.items); setSelected(current=>data.items.find(item=>item.id===current?.id)??data.items[0]); setMessage("");}catch{setMessage("Orders could not be loaded.");}},[]);
  useEffect(()=>{void load();},[load]);
  return <div className="orders-workspace"><div className="orders-toolbar"><div><strong>{items.length}</strong><span>enquiries and orders</span></div><button onClick={()=>void load()} aria-label="Refresh orders"><RefreshCw size={17}/></button></div>{message&&<p role="status">{message}</p>}<div className="orders-layout"><div className="order-list">{items.map(item=><button className={selected?.id===item.id?"active":""} key={item.id} onClick={()=>setSelected(item)}><span><strong>{item.reference}</strong><small>{item.productName} × {item.quantity}</small></span><span className={`order-state state-${item.status}`}>{item.status.replaceAll("_"," ")}</span><small>{item.customerName} · {item.customerPhone}</small></button>)}</div>{selected?<OrderAction item={selected} onSaved={load}/>:<div className="orders-empty">New WhatsApp enquiries appear here.</div>}</div></div>;
}

function OrderAction({item,onSaved}:{item:SalesCase;onSaved:()=>Promise<void>}) {
  const [message,setMessage]=useState(""); const action=next[item.status];
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault(); if(!action)return; const values=Object.fromEntries(new FormData(event.currentTarget).entries()); const body:{status:Status;reason:string;totalMinor?:number;billNumber?:string;collectionNote?:string}={status:action.status,reason:String(values.reason)}; if(values.total)body.totalMinor=Math.round(Number(values.total)*100); if(values.billNumber)body.billNumber=String(values.billNumber); if(values.collectionNote)body.collectionNote=String(values.collectionNote); const response=await fetch(`/api/v1/admin/walk-in-orders/${item.id}/transition`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(body)}); const data=await response.json() as {whatsappUrl?:string}; if(!response.ok)return setMessage("The state change was rejected."); setMessage("Saved. WhatsApp message is ready."); await onSaved(); if(data.whatsappUrl)window.open(data.whatsappUrl,"_blank","noopener,noreferrer");}
  return <aside className="order-action"><p>Selected request</p><h2>{item.reference}</h2><dl><div><dt>Customer</dt><dd>{item.customerName}</dd></div><div><dt>WhatsApp</dt><dd>{item.customerPhone}</dd></div><div><dt>Product</dt><dd>{item.productName} × {item.quantity}</dd></div><div><dt>Agreed total</dt><dd>{item.totalMinor===null?"Not confirmed":`₹${(item.totalMinor/100).toLocaleString("en-IN",{minimumFractionDigits:2})}`}</dd></div><div><dt>Bill</dt><dd>{item.billNumber??"Not prepared"}</dd></div></dl>{action?<form onSubmit={submit}>{item.status==="received"&&<label>Agreed total (₹)<input name="total" type="number" min="1" step="0.01" required/></label>}{item.status==="confirmed"&&<label>Bill number<input name="billNumber" required/></label>}{item.status==="billed"&&<label>Collection instructions<textarea name="collectionNote" required defaultValue="Your order is ready. Please visit the store with this reference."/></label>}<label>Reason or note<textarea name="reason" required minLength={2}/></label><button type="submit"><MessageCircle size={17}/>{action.label} and message</button></form>:<div className="order-complete"><CheckCircle2/>{item.status==="collected"?"Collection complete.":"This order is closed."}</div>}{message&&<p role="status">{message}</p>}</aside>;
}
