export type TenantPublicPageKey =
  | "home"
  | "workspace"
  | "features"
  | "security"
  | "blog"
  | "updates"
  | "about"
  | "team"
  | "contact"
  | "support"
  | "order-help"
  | "shipping"
  | "returns"
  | "cookies"
  | "privacy"
  | "terms";
